[project]
name = "pruning-algorithms-research-project"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "torch",
    "torchvision",
    "numpy",
    "pandas",
    "scipy",
    "matplotlib",
    "scikit-learn",
    "seaborn",
    "ipykernel",
    "notebook",
    "wandb",
    "pyyaml",
    "tqdm",
]
